image: mohamnag/gradle

stages:
  - test

gradlebuld:
  stage: test
  script:
   - gradle -q build
  except:
  - /^release-.*$/ # use regexp ;-)
  tags:
    - docker

releasebuild:
  stage: test
  script:
   - gradle -q build
   - mkdir -p Argon
   - cp -r build/libs Argon/
   - cp -r build/resources Argon/
   - cp build/resources/main/plugin.xml Argon/
  only:
  - /^release-.*$/ # use regexp ;-)
  tags:
    - docker
  artifacts:
    paths:
    - Argon
